/**
 * Test ideas per field type: [category, idea, example input, expected result].
 * Written from day-to-day QA practice; used by the Testing Lab generator.
 */

export const CATEGORIES = {
  pos: { label: "Happy path", icon: "fa-solid fa-circle-check" },
  edge: { label: "Boundary", icon: "fa-solid fa-ruler" },
  neg: { label: "Negative", icon: "fa-solid fa-circle-xmark" },
  sec: { label: "Security", icon: "fa-solid fa-shield-halved" },
  a11y: { label: "Accessibility", icon: "fa-solid fa-universal-access" },
  perf: { label: "Resilience", icon: "fa-solid fa-gauge-high" },
};

export const FIELDS = [
  {
    id: "email",
    label: "Email field",
    icon: "fa-solid fa-at",
    ideas: [
      ["pos", "Accepts a plain valid address", "user@example.com", "the address is accepted"],
      ["pos", "Accepts plus addressing", "user+qa@example.com", "the address is accepted"],
      ["pos", "Accepts multi-level domains", "user@mail.example.co.uk", "the address is accepted"],
      ["edge", "Local part of exactly 64 characters", "a×64@example.com", "the address is accepted"],
      ["edge", "Local part of 65 characters", "a×65@example.com", "a clear length error is shown"],
      ["edge", "Total length above 254 characters", "a×250@example.com", "a clear length error is shown"],
      ["neg", "Missing @ sign", "userexample.com", "an inline format error is shown"],
      ["neg", "Consecutive dots in the local part", "user..name@example.com", "the address is rejected"],
      ["neg", "Leading and trailing spaces", " user@example.com ", "input is trimmed or rejected consistently"],
      ["neg", "Empty submit on a required field", "", "a required-field message is shown"],
      ["neg", "Case-only duplicate of an existing account", "User@Example.com", "it is treated as the same address"],
      ["sec", "Script tag in the address", "<script>alert(1)</script>@x.com", "input is escaped and no script runs"],
      ["sec", "SQL-style payload", "' OR 1=1 --@x.com", "the request is rejected without a server error"],
      ["a11y", "Error message is announced", "invalid", "the error is linked via aria-describedby and read by screen readers"],
      ["a11y", "Correct input type and autocomplete", "", "type=email and autocomplete=email are set for mobile keyboards"],
    ],
  },
  {
    id: "password",
    label: "Password",
    icon: "fa-solid fa-key",
    ideas: [
      ["pos", "Meets every policy rule", "Str0ng!Passphrase", "the password is accepted"],
      ["edge", "One character below minimum length", "Ab1!xyz", "a length rule message is shown"],
      ["edge", "Exactly the minimum length", "Ab1!xyzw", "the password is accepted"],
      ["edge", "Very long passphrase (128+ chars)", "x×129", "accepted, or a clear max-length message"],
      ["neg", "Common breached password", "Password123", "rejected as too common"],
      ["neg", "Whitespace only", "        ", "rejected with a helpful message"],
      ["neg", "Unicode and emoji", "p@ss🙂word", "handled consistently at signup and login"],
      ["sec", "Masked by default with a show toggle", "", "characters are hidden until the toggle is used"],
      ["sec", "Lockout or throttling after repeated failures", "wrong ×10", "further attempts are rate-limited"],
      ["sec", "Never appears in URLs, logs or analytics", "", "no plaintext password in network traces"],
      ["sec", "Paste is allowed", "pasted from a manager", "paste works (password managers stay usable)"],
      ["a11y", "Rules are visible before typing", "", "requirements are listed and announced"],
      ["a11y", "Caps Lock warning", "CAPS ON", "a non-blocking warning appears"],
    ],
  },
  {
    id: "search",
    label: "Search box",
    icon: "fa-solid fa-magnifying-glass",
    ideas: [
      ["pos", "Exact term returns relevant results", "playwright", "matching results are listed first"],
      ["pos", "Typo tolerance", "playwrigt", "results or a 'did you mean' suggestion"],
      ["edge", "Empty query", "", "sensible default or a prompt, not an error"],
      ["edge", "Very long query (1,000 chars)", "q×1000", "handled without a crash or 5xx"],
      ["neg", "Wildcard characters are literal", "% _ * ?", "no unexpected match-all behaviour"],
      ["neg", "No results", "zzqxj", "a helpful empty state with next steps"],
      ["sec", "Reflected XSS in the 'results for' heading", "<img src=x onerror=alert(1)>", "the query is escaped"],
      ["sec", "Injection string", "'; DROP TABLE items;--", "treated as text; no server error"],
      ["perf", "Typing is debounced", "type quickly", "one request per pause, not per keystroke"],
      ["perf", "Out-of-order responses", "fast typing on slow network", "only the latest query's results show"],
      ["a11y", "Result count announced", "", "an aria-live region announces the count"],
      ["a11y", "Suggestions are keyboard navigable", "↑ ↓ Enter", "arrow keys move, Enter selects, Esc closes"],
    ],
  },
  {
    id: "date",
    label: "Date picker",
    icon: "fa-regular fa-calendar",
    ideas: [
      ["pos", "Pick a valid date", "15 Mar 2026", "the date is saved exactly"],
      ["edge", "29 February in a leap year", "29/02/2028", "accepted"],
      ["edge", "29 February in a non-leap year", "29/02/2027", "rejected"],
      ["edge", "Minimum and maximum allowed dates", "min / max", "both accepted; one day outside rejected"],
      ["edge", "Midnight in another time zone", "23:59 → 00:00", "stored date does not shift by a day"],
      ["edge", "Daylight-saving transition day", "DST change date", "durations and times stay correct"],
      ["neg", "Impossible typed date", "31/04/2026", "rejected with a clear message"],
      ["neg", "End date before start date", "start 10, end 5", "rejected before submit"],
      ["neg", "Ambiguous locale format", "03/04/2026", "interpreted per locale and shown unambiguously"],
      ["a11y", "Keyboard-only selection", "Tab, arrows, Enter", "every date is reachable without a mouse"],
      ["a11y", "Selected date is announced", "", "screen readers read the full date"],
    ],
  },
  {
    id: "upload",
    label: "File upload",
    icon: "fa-solid fa-file-arrow-up",
    ideas: [
      ["pos", "Allowed type within size", "report.pdf (2 MB)", "uploads with progress feedback"],
      ["edge", "Exactly the maximum size", "max bytes", "accepted"],
      ["edge", "One byte over the maximum", "max + 1 byte", "rejected before the upload starts"],
      ["edge", "Zero-byte file", "empty.txt", "rejected or handled explicitly"],
      ["neg", "Disallowed extension", "script.exe", "rejected with the allowed types listed"],
      ["neg", "Renamed extension (content check)", "virus.exe → photo.png", "rejected by content, not by name"],
      ["neg", "Unusual file names", "my résumé (final) ✓.pdf", "stored and displayed correctly"],
      ["sec", "Path traversal in the file name", "../../etc/passwd", "the name is sanitised"],
      ["sec", "SVG with embedded script", "evil.svg", "script never executes when viewed"],
      ["sec", "Anti-virus test file", "EICAR test string", "flagged and quarantined"],
      ["perf", "Connection drops mid-upload", "offline at 50%", "clear error with retry, no ghost file"],
      ["a11y", "Drag-and-drop has a keyboard alternative", "", "a labelled button opens the file picker"],
    ],
  },
  {
    id: "amount",
    label: "Payment amount",
    icon: "fa-solid fa-money-bill-wave",
    ideas: [
      ["pos", "Normal amount", "10.00", "charged exactly 10.00"],
      ["edge", "Smallest allowed amount", "0.01", "accepted"],
      ["edge", "Zero", "0", "rejected"],
      ["edge", "Just above the limit", "limit + 0.01", "rejected with the limit shown"],
      ["edge", "Too many decimals", "10.005", "rounded by a documented rule, or rejected"],
      ["neg", "Negative value", "-5", "rejected"],
      ["neg", "Scientific notation", "1e3", "rejected or clearly interpreted"],
      ["neg", "Locale separators", "1.000,50 vs 1,000.50", "parsed per locale with no silent 1000x errors"],
      ["edge", "Zero- and three-decimal currencies", "JPY 500 / KWD 1.250", "decimals follow the currency"],
      ["sec", "Amount tampered in the request payload", "edit JSON to 0.01", "the server recalculates and rejects"],
      ["perf", "Double-click on Pay", "click ×2", "exactly one charge (idempotency key)"],
      ["a11y", "Currency is not only a symbol", "", "screen readers hear the currency name"],
    ],
  },
  {
    id: "api",
    label: "REST API: POST /users",
    icon: "fa-solid fa-plug",
    ideas: [
      ["pos", "Valid payload creates a user", '{"name":"Ada","email":"ada@x.io"}', "201 and the body matches the contract schema"],
      ["neg", "Missing required field", '{"name":"Ada"}', "400 with a field-level error"],
      ["neg", "Invalid format", '{"email":"not-an-email"}', "422 with a validation message"],
      ["neg", "Duplicate resource", "same email twice", "409 Conflict"],
      ["sec", "No auth token", "no Authorization header", "401"],
      ["sec", "Token without the right scope", "read-only token", "403"],
      ["sec", "Mass assignment", '{"role":"admin"}', "role is ignored or rejected"],
      ["neg", "Wrong content type", "text/plain body", "415 Unsupported Media Type"],
      ["edge", "Oversized payload", "5 MB body", "413 Payload Too Large"],
      ["perf", "Rate limiting", "burst of 200 requests", "429 with a Retry-After header"],
      ["perf", "Safe retries", "same Idempotency-Key twice", "one user created"],
      ["perf", "Latency budget", "load test", "p95 stays under the agreed threshold"],
    ],
  },
];

export const FLAKY = [
  {
    symptom: "Passes locally, fails in CI",
    cause: "Different browser versions, CPU speed, screen size or env vars.",
    fix: "Pin versions, run tests in the same container locally and in CI, and wait for conditions instead of fixed sleeps.",
  },
  {
    symptom: "Fails only when run with the full suite",
    cause: "Shared state or order dependence: tests reuse data, cookies or DB rows.",
    fix: "Give each test its own data, reset state in hooks, and run in random order to catch it early.",
  },
  {
    symptom: "“Element not found” now and then",
    cause: "The test raced the UI: it clicked before render or hydration finished.",
    fix: "Use auto-waiting locators and web-first assertions (expect(locator).toBeVisible()), never sleep().",
  },
  {
    symptom: "Breaks at midnight or month end",
    cause: "Hidden assumptions about dates, time zones or daylight saving.",
    fix: "Freeze the clock in tests and assert in UTC. Add explicit cases for time-zone boundaries.",
  },
  {
    symptom: "Random 5xx or timeouts",
    cause: "A real third-party dependency is slow, rate-limited or down.",
    fix: "Mock external services at the network layer and keep a few contract tests against the real thing.",
  },
  {
    symptom: "Visual diffs that nobody can see",
    cause: "Font rendering, anti-aliasing, animations or dynamic content like dates and avatars.",
    fix: "Disable animations, mask dynamic areas, use a fixed viewport and one Docker image for baselines.",
  },
  {
    symptom: "Unique constraint errors in parallel runs",
    cause: "Workers generate the same test data at the same time.",
    fix: "Add a run ID and worker index to generated data, or give each worker its own schema.",
  },
  {
    symptom: "Retries make it green",
    cause: "Retries hide real race conditions, and some of those are product bugs.",
    fix: "Track the flake rate per test, quarantine repeat offenders, and fix the root cause instead of raising retries.",
  },
];
