import { lazy } from "react";

/**
 * The Tech Universe channel lineup. Channels are grouped into four bands and
 * numbered like a broadcast guide. Each page is its own code-split chunk, so
 * the hub stays light and a page's code only loads when someone opens it.
 */
export const BANDS = [
  { id: "signal", label: "Signal" },
  { id: "ai", label: "AI" },
  { id: "build", label: "Build" },
  { id: "play", label: "Play" },
];

export const MODULES = [
  {
    id: "news",
    channel: "01",
    band: "signal",
    title: "Newsroom",
    short: "News",
    tagline: "Every headline worth reading, merged into one live feed.",
    hue: 12,
    source: "Hacker News · DEV · GitHub",
    Component: lazy(() => import("./modules/Newsroom")),
  },
  {
    id: "launches",
    channel: "02",
    band: "signal",
    title: "Launchpad",
    short: "Launches",
    tagline: "What developers shipped this week.",
    hue: 28,
    source: "Show HN · Hugging Face · GitHub",
    Component: lazy(() => import("./modules/Launchpad")),
  },
  {
    id: "status",
    channel: "03",
    band: "signal",
    title: "Internet Status",
    short: "Status",
    tagline: "Is it down, or is it just you?",
    hue: 150,
    source: "13 public status pages",
    Component: lazy(() => import("./modules/InternetStatus")),
  },
  {
    id: "history",
    channel: "04",
    band: "signal",
    title: "Time Machine",
    short: "History",
    tagline: "What happened in tech on this day.",
    hue: 212,
    source: "Wikipedia On This Day",
    Component: lazy(() => import("./modules/TimeMachine")),
  },
  {
    id: "models",
    channel: "05",
    band: "ai",
    title: "Model Radar",
    short: "Models",
    tagline: "Trending open models and every new LLM, with prices.",
    hue: 262,
    source: "Hugging Face · OpenRouter",
    Component: lazy(() => import("./modules/ModelRadar")),
  },
  {
    id: "papers",
    channel: "06",
    band: "ai",
    title: "Paper Radar",
    short: "Papers",
    tagline: "Today's most upvoted AI research.",
    hue: 40,
    source: "Hugging Face Daily Papers · arXiv",
    Component: lazy(() => import("./modules/PaperRadar")),
  },
  {
    id: "ai-engineer",
    channel: "07",
    band: "ai",
    title: "AI Engineer Kit",
    short: "AI Kit",
    tagline: "Free LLM APIs, real costs and a roadmap.",
    hue: 168,
    source: "OpenRouter catalogue",
    Component: lazy(() => import("./modules/AIEngineerKit")),
  },
  {
    id: "testing",
    channel: "08",
    band: "build",
    title: "Testing Lab",
    short: "Testing",
    tagline: "Framework wars and a test-idea generator.",
    hue: 192,
    source: "npm registry",
    Component: lazy(() => import("./modules/TestingLab")),
  },
  {
    id: "studio",
    channel: "09",
    band: "build",
    title: "Dev Studio",
    short: "Studio",
    tagline: "Make badges, commits and cron schedules.",
    hue: 330,
    source: "shields.io · built-in tools",
    Component: lazy(() => import("./modules/Studio")),
  },
  {
    id: "contribute",
    channel: "10",
    band: "build",
    title: "Contribute",
    short: "Contribute",
    tagline: "Your first open-source pull request starts here.",
    hue: 128,
    source: "GitHub Search",
    Component: lazy(() => import("./modules/Contribute")),
  },
  {
    id: "music",
    channel: "11",
    band: "play",
    title: "Music",
    short: "Music",
    tagline: "Real tracks for deep work, with visuals locked to the beat.",
    hue: 74,
    source: "Audius · SomaFM",
    Component: lazy(() => import("./modules/Music")),
  },
  {
    id: "arcade",
    channel: "12",
    band: "play",
    title: "Dev Arcade",
    short: "Arcade",
    tagline: "Three games that make you a sharper engineer.",
    hue: 300,
    source: "Plays in your browser",
    Component: lazy(() => import("./modules/Arcade")),
  },
  {
    id: "screen",
    channel: "13",
    band: "play",
    title: "Watch & Read",
    short: "Screen",
    tagline: "Films, series and books about the people who built tech.",
    hue: 48,
    source: "TVmaze · Wikipedia · Open Library",
    Component: lazy(() => import("./modules/WatchRead")),
  },
];

const ALIASES = { radio: "music" };

export const moduleById = (id) => MODULES.find((module) => module.id === (ALIASES[id] || id));
export const aliasOf = (id) => ALIASES[id] || null;
